[build]
  command = "npm install --legacy-peer-deps --no-fund --no-audit && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  command = "npm install --legacy-peer-deps --no-fund --no-audit && npm run build"

[context.deploy-preview]
  command = "npm install --legacy-peer-deps --no-fund --no-audit && npm run build"

[context.branch-deploy]
  command = "npm install --legacy-peer-deps --no-fund --no-audit && npm run build"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, immutable, max-age=31536000"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"