services:
  - type: web
    name: credify-marketplace
    env: node
    buildCommand: bun install && bun run build
    startCommand: node server.js
    plan: free

  - type: web
    name: credify-backend
    env: node
    rootDir: backend
    buildCommand: bun install && bun run build
    startCommand: node dist/index.js
    envVars:
      - key: MONGODB_URI
        value: mongodb://localhost:27017/credify
      - key: PORT
        value: 4000
      - key: CORS_ORIGIN
        value: https://credify-marketplace.onrender.com
